services:
  backup:
    image: rodriguestiago0/actualbudget-backup:latest
    restart: always
    environment:
    #   RCLONE_REMOTE_NAME: 'ActualBudgetBackup'
    #   RCLONE_REMOTE_DIR: '/ActualBudgetBackup/'
    #   RCLONE_GLOBAL_FLAG: ''
        ACTUAL_BUDGET_URL: 'https://actual.example.com'
        ACTUAL_BUDGET_PASSWORD: ''
        ACTUAL_BUDGET_SYNC_ID: ''
    #   ACTUAL_BUDGET_E2E_PASSWORD: ''
    #   CRON: '0 0 * * *'
    #   BACKUP_FILE_SUFFIX: '%Y%m%d'
    #   BACKUP_KEEP_DAYS: 0
    #   TIMEZONE: 'UTC'
    #   DISPLAY_NAME: 'Actual Budget'
    #   TELEGRAM_BOT_TOKEN: ''
    #   TELEGRAM_CHAT_ID: ''
    #   TELEGRAM_MESSAGE_THREAD_ID: ''
    #   TELEGRAM_PARSE_MODE: ''
    #   TELEGRAM_DISABLE_NOTIFICATION: 'FALSE'
    #   TELEGRAM_WHEN_START: 'TRUE'
    #   TELEGRAM_WHEN_SUCCESS: 'TRUE'
    #   TELEGRAM_WHEN_FAILURE: 'TRUE'
    volumes:
      - actualbudget-rclone-data:/config/
    #   - /path/to/env:/.env
    
volumes:
  actualbudget-rclone-data:
    external: true
    name: actualbudget-rclone-data
